name = "chart-img-telegram-bot"

main = "src/index.js"
compatibility_date = "2022-11-30"


[vars]
NGROK_TOKEN = ""
CHART_IMG_API_KEY = ""
TELEGRAM_API_TOKEN = ""
TELEGRAM_SECRET_TOKEN = "somethingRandomHere"
